version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: blog-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: azerty

  express-app:
    build: .
    container_name: express-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://admin:azerty@mongodb:27017/blog_mern?authSource=admin
    depends_on:
      - mongodb
